name = "papercitation"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[assets]
directory = "public"

routes = [
  { pattern = "papercitation.com", custom_domain = true },
  { pattern = "www.papercitation.com", custom_domain = true }
]